export const questionsList = {
  questions: [
    {
      id: 1,
      no: "Which of the following is the correct name of React.js?",
      value: "React.js",
      name: "ReactJs",
      options: ["React", "React.js", "ReactJS", "All of the above"],
    },
    {
      id: 2,
      no: "Which of the following command is used to install create-react-app?",
      value: "npm install -g create-react-app",
      name:'npmInstall',
      options: [
        "npm install -g create-react-app",
        "npm install create-react-app",
        "npm install -f create-react-app",
        "install -g create-react-app",
      ],
    },
    {
      id: 3,
      no: "What of the following is used in React.js to increase performance?",
      value: "Virtual DOM",
      name:'virtualDom',
      options: [
        "Original DOM",
        "Virtual DOM",
        "Both A and B",
        "None of the above",
      ],
    },
    {
      id: 4,
      no: "Which of the following keyword is used to create a class inheritance?",
      value: "Extends",
      name:'extends',
      options: ["Create", "Inherits", "Extends", "This"],
    },
    {
      id: 5,
      no: "How many ways of defining your variables in ES6?",
      value: "4",
      name:'numbers',
      options: ["1", "3", "4", "5"],
    },
    {
      id: 6,
      no: "What are the two ways to handle data in React?",
      value: "State & Props",
      name:'stateProps',
      options: [
        "State & Props",
        "Services & Components",
        "State & Services",
        "State & Component",
      ],
    },
    {
      id: 7,
      no: "Using which of the following command can prevent default behaviour at in react?",
      value: "preventDefault()",
      name:'preventDefault',
      options: [
        "preventDefault()",
        "avoidDefault()",
        "revokeDefault()",
        "None of the above",
      ],
    },
    {
      id: 8,
      no: "Which company developed ReactJS?",
      value: "Apple",
      name:'apple',
      options: ["Apple", "Facebook", "Google", "Twitter"],
    },
    {
      id: 9,
      no: "Which of the following is method is not a part of ReactDOM?",
      value: "ReactDOM.destroy()",
      name:'reactDomDestroy',
      options: [
        "ReactDOM.hydrate()",
        "ReactDOM.destroy()",
        "ReactDOM.createPortal()",
        "All of the above",
      ],
    },
    {
      id: 10,
      no: "React.js is written in which of the following language?",
      value: "Javascript",
      name:'javascript',
      options: ["C", "C++", "Javascript", "Java"],
    },
  ],
};
